### ISSUE TITLE
`tree_from_buf` hangs when parsing a small test case

### ISSUE THREAD

**Issue by OctavioGalland** [AFLplusplus/Grammar-Mutator#36]
## Environment

Ubuntu 20.04.1 on amd64. Grammar-mutator commit `cbe5e32752773945e0142fac9f1b7a0ccb5dcdff` and afl++ version `4.01a`

## Description

The grammar mutator takes an exceptionally long time to generate a tree from a given input (even when that input is empty) when using a custom grammar file attached below. More specifically, it hangs at the function `tree_from_buf`, a complete backtrace is included below.
I suspect this might have to do with the grammar file, since I haven't been able to reproduce the bug with other grammars. But since it is also true that the generated test case is the simplest possible case according to the grammar, I am unsure as to what might be causing it.

This is concerning because a fuzzing campaign using this grammar can only be started from a few (at most) inputs, and when interrupted the campaign cannot be resumed since the time cost becomes prohibitive.

## How to reproduce

- Build Grammar-Mutator using the file attached below with `make ENABLE_DEBUG=1 GRAMMAR_FILE=python.json`
- We don't need any specific instrumented binary, since the issue takes place before the fuzzing starts, so I am going to use `echo` as an example
- Generate a simple test case: `grammar_generator-python 1 50 in out/default/trees`. In my case the generated input was:
```
a=1
b=1.203213
foo='123213'
bar=b'123\x01'
1=a

```
which is one of the simplest test cases possible according to the grammar. With tree file (base64 encoded):
```
AQAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAArAAAAYT0xCmI9MS4y
MDMyMTMKZm9vPScxMjMyMTMnCmJhcj1iJzEyM1x4MDEnCgMAAAAAAAAAAgAAAAAAAAAKAAAAAAAA
AAEAAAAAAAAACwAAAAAAAAACAAAAAAAAAAwAAAAAAAAAAQAAAAAAAAAOAAAAAAAAAAIAAAAAAAAA
DwAAAAAAAAABAAAAAAAAAC8AAAAAAAAAAQAAAAAAAAAzAAAAAAAAAAEAAAAAAAAANAAAAAAAAAAB
AAAAAAAAADUAAAAAAAAAAQAAAAAAAAA2AAAAAAAAAAEAAAAAAAAAOQAAAAAAAAABAAAAAAAAADoA
AAAAAAAAAQAAAAAAAAA7AAAAAAAAAAEAAAAAAAAAPAAAAAAAAAABAAAAAAAAAD0AAAAAAAAAAQAA
AAAAAAA+AAAAAAAAAAEAAAAAAAAAPwAAAAAAAAABAAAAAAAAAEEAAAAAAAAAAgAAAAAAAABDAAAA
AQAAAAEAAAAAAAAAXAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAxQAAAAAAAAAAAAAAA
AAAAAA0AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAAAAPQ8AAAAAAAAAAQAAAAAAAAAvAAAA
AAAAAAEAAAAAAAAAMwAAAAAAAAABAAAAAAAAADQAAAAAAAAAAQAAAAAAAAA1AAAAAAAAAAEAAAAA
AAAANgAAAAAAAAABAAAAAAAAADkAAAAAAAAAAQAAAAAAAAA6AAAAAAAAAAEAAAAAAAAAOwAAAAAA
AAABAAAAAAAAADwAAAAAAAAAAQAAAAAAAAA9AAAAAAAAAAEAAAAAAAAAPgAAAAAAAAABAAAAAAAA
AD8AAAAAAAAAAQAAAAAAAABBAAAAAAAAAAIAAAAAAAAAQwAAAAAAAAABAAAAAAAAAFgAAAAAAAAA
AQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAYUAAAAAAAAAAAAAAAAAAAABaAAAAAAAAAAEAAAAAAAAA
AAAAAAAAAAAAAAAAAQAAAApaAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAo=
```
- Start fuzzing: `AFL_CUSTOM_MUTATOR_ONLY=1 AFL_CUSTOM_MUTATOR_LIBRARY=libgrammarmutator-python.so afl-fuzz -i in -o out -- ./echo @@`

The grammar file is:
```
# python.json
{
	"<START>": [["<defs>", "<program>"]],
	"<defs>": [["a=1\nb=1.203213\nfoo='123213'\nbar=b'123\\x01'\n"]],
	"<program>": [["<stmt>", "<NEWLINE>"], ["<stmt>", "<NEWLINE>", "<program>"]],
	
	"<decorator>": [["@", "<dotted_name>", "(", "<arglist>", ")", "<NEWLINE>"],
		["@", "<dotted_name>", "<NEWLINE>"]],
	"<decorators>": [["<decorator>"], ["<decorator>", "<decorators>"]],
	"<decorated>": [["<decorators>", "<classdef>"], ["<decorators>", "<funcdef>"]],
	"<funcdef>": [["def ", "<NAME>", "<parameters>", "->", "<test>", ":", "<suite>"],
		["def ", "<NAME>", "<parameters>", ":", "<suite>"]],
	"<parameters>": [["(", ")"], ["(", "<typedargslist>", ")"]],
	"<typedargslist>": [
		["<NAME>", ", ", "<typedargslist>"], ["<NAME>"], ["*", "<NAME>"], ["**", "<NAME>"], ["*", "<NAME>", ", ", "**", "<NAME>"], []
	],
	
	"<stmt>": [["<simple_stmt>"], ["<compound_stmt>"]],
	"<simple_stmt>": [["<small_stmt>", "<NEWLINE>"], ["<small_stmt>", ";", "<simple_stmt>"]],
	"<small_stmt>": [["<expr_stmt>"], ["<del_stmt>"], ["<pass_stmt>"], ["<flow_stmt>"],
		["<import_stmt>"], ["<global_stmt>"], ["<nonlocal_stmt>"], ["<assert_stmt>"]],
	"<aux_equals_sequence>": [["=", "<testlist_star_expr>"], ["=", "<yield_expr>"],
		["=", "<testlist_star_expr>", "<aux_equals_sequence>"], ["=", "<yield_expr>", "<aux_equals_sequence>"]],
	"<expr_stmt>": [["<testlist_star_expr>", "<augassign>", "<yield_expr>"],
		["<testlist_star_expr>", "<augassign>", "<testlist>"],
		["<testlist_star_expr>", "<aux_equals_sequence>"]],
	"<testlist_star_expr>": [["<test>"], ["<star_expr>"], ["<star_expr>", ",", "<testlist_star_expr>"],
		["<test>", ",", "<testlist_star_expr>"]],
	"<augassign>": [["+="], ["-="], ["*="], ["/="], ["%="],  ["&="],  ["|="],  ["^="], 
		["<<="],  [">>="],  ["**="],  ["//="]],
	"<del_stmt>": [["del ", "<exprlist>"]],
	"<pass_stmt>": [["pass"]],
	"<flow_stmt>": [["<break_stmt>"], ["<continue_stmt>"], ["<return_stmt>"], ["<raise_stmt>"], ["<yield_stmt>"]],
	"<break_stmt>": [["break"]],
	"<continue_stmt>": [["continue"]],
	"<return_stmt>": [["return ", "<testlist>"], ["return"]],
	"<yield_stmt>": [["<yield_expr>"]],
	"<raise_stmt>": [["raise"], ["raise ", "<test>"], ["raise ", "<test>", " from ", "<test>"]],
	"<import_stmt>": [["<import_name>"]],
	"<import_name>": [["import ", "<dotted_import_as_names>"]],
	"<dotted_import_as_name>": [["<dotted_import_name>"], ["<dotted_import_name>", " as ", "<NAME>"]],
	"<dotted_import_as_names>": [["<dotted_import_as_name>"], ["<dotted_import_as_name>", ", ", "<dotted_import_as_names>"]],
	"<aux_trailing_dots>": [[".", "<NAME>", "<aux_trailing_dots>"], [".", "<NAME>"]],
	"<dotted_import_name>": [["<IMODULE_NAME>"], ["<IMODULE_NAME>", "<aux_trailing_dots>"]],
	"<dotted_name>": [["<NAME>"], ["<IMODULE_NAME>"], ["<NAME>", "<aux_trailing_dots>"], ["<IMODULE_NAME>", "<aux_trailing_dots>"]],
	"<global_stmt>": [["global ", "<NAME>"]],
	"<nonlocal_stmt>": [["nonlocal ", "<NAME>"]],
	"<assert_stmt>": [["assert ", "<test>"]],
	"<compound_stmt>": [["<if_stmt>"], ["<while_stmt>"], ["<for_stmt>"], 
		["<try_stmt>"], ["<with_stmt>"], ["<funcdef>"], ["<classdef>"], ["<decorated>"]],
	"<aux_elif_stmts>": [[], ["elif ", "<test>", ":", "<suite>", "<aux_elif_stmts>"]],
	"<if_stmt>": [["if ", "<test>", ":", "<suite>", "<aux_elif_stmts>"], ["if ", "<test>", ":", "<suite>", "<aux_elif_stmts>", "else", ":", "<suite>"]],
	"<while_stmt>": [["while ", "<test>", ":", "<suite>"], ["while ", "<test>", ":", "<suite>", "else", ":", "<suite>"]],
	"<for_stmt>": [["for ", "<exprlist>", " in ", "<testlist>", " : ", "<suite>"],
		["for ", "<exprlist>", " in ", "<testlist>", ":", "<suite>", "else", ":", "<suite>"]],
	"<aux_except_seq>": [["<except_clause>", ":", "<suite>"], ["<except_clause>", ":", "<suite>", "<aux_except_seq>"]],
	"<try_stmt>": [["try", ":", "<suite>", "<aux_except_seq>", "else", ":", "<suite>"],
		["try", ":", "<suite>", "<aux_except_seq>", "finally", ":", "<suite>"],
		["try", ":", "<suite>", "<aux_except_seq>", "else", ":", "<suite>", "finally", ":", "<suite>"],
		["try", ":", "<suite>", "finally", ":", "<suite>"]],
	"<with_stmt>": [["with ", "<with_item>", ":", "<suite>"]],
	"<with_item>": [["<test>"], ["<test>", " as ", "<expr>"]],
	"<except_clause>": [["except"], ["except ", "<test>"], ["except ", "<test>", " as ", "<NAME>"]],
	"<aux_stmt_seq>": [["<stmt>"], ["<stmt>", "<aux_stmt_seq>"]],
	"<suite>": [["<simple_stmt>"], ["<NEWLINE>", "arrancalasuite", "<NEWLINE>", "<aux_stmt_seq>", "<NEWLINE>", "terminalasuite", "<NEWLINE>"]],
	"<test>": [["<or_test>", " if ", "<or_test>", " else ", "<test>"],
		["<or_test>"], ["<lambdef>"]],
	"<test_nocond>": [["<or_test>"], ["<lambdef_nocond>"]],
	"<lambdef>": [["lambda ", "<typedargslist>", ":", "<test>"], ["lambda ", ":", "<test>"]],
	"<lambdef_nocond>": [["lambda ", "<typedargslist>", ":", "<test_nocond>"], ["lambda ", ":", "<test_nocond>"]],
	"<or_test>": [["<and_test>"], ["<and_test>", " or ", "<or_test>"]],
	"<and_test>": [["<not_test>"], ["<not_test>", " and ", "<and_test>"]],
	"<not_test>": [["not ", "<not_test>"], ["<comparison>"]],
	"<comparison>": [["<expr>"], ["<expr>", "<comp_op>", "<comparison>"]],
	"<comp_op>": [["<"], [">"], ["=="], [">="], ["<="], ["!="], [" in "], [" not in "], [" is "], [" is not "]],
	"<star_expr>": [["*", "<expr>"]],
	"<expr>": [["<xor_expr>"], ["<xor_expr>", "|", "<expr>"]],
	"<xor_expr>": [["<and_expr>"], ["<and_expr>", "^", "<xor_expr>"]],
	"<and_expr>": [["<shift_expr>"], ["<shift_expr>", "&", "<and_expr>"]],
	"<shift_expr>": [["<arith_expr>"], ["<arith_expr>", "<<", "<shift_expr>"], ["<arith_expr>", ">>", "<shift_expr>"]],
	"<arith_expr>": [["<term>"], ["<term>", "+", "<arith_expr>"], ["<term>", "-", "<arith_expr>"]],
	"<term>": [["<factor>"],
		["<factor>", "*", "<term>"],
		["<factor>", "/", "<term>"],
		["<factor>", "%", "<term>"],
		["<factor>", "//", "<term>"]],
	"<factor>": [["+", "<factor>"],
		["-", "<factor>"],
		["~", "<factor>"],
		["<power>"]],
	"<aux_trailer_seq>": [[], ["<trailer>", "<aux_trailer_seq>"]],
	"<power>": [["<atom>", "<aux_trailer_seq>"],
		["<atom>", "<aux_trailer_seq>", "**", "<factor>"]],
	"<aux_string_seq>": [["<STRING>"], ["<STRING>", "<aux_string_seq>"]],
	"<atom>": [["<NAME>"], ["<NUMBER>"], ["<aux_string_seq>"], ["..."], ["None"], ["True"], ["False"],
		["[]"], ["{}"], ["[", "<testlist_comp>", "]"], ["{", "<dictorsetmaker>", "}"], ["()"],
		["(", "<yield_expr>", ")"], ["(", "<testlist_comp>", ")"]],
	"<aux_test_star_seq>": [[], [",", "<test>", "<aux_test_star_seq"], [",", "<star_expr>", "<aux_test_star_seq>"]],
	"<testlist_comp>": [["<test>", "<comp_for>"], ["<star_expr>", "<comp_for>"],
		["<test>", "<aux_test_star_seq>"], ["<star_expr>", "<aux_test_star_seq>"]],
	"<trailer>": [["()"], ["(", "<arglist>", ")"], ["[]"], ["[", "<subscriptlist>", "]"], [".", "<NAME>"]],
	"<subscriptlist>": [["<subscript>"], ["<subscript>", ",", "<subscriptlist>"]],
	"<subscript>": [["<test>"], [":"], ["<test>", ":"], [":", "<test>"], [":", "<sliceop>"], ["<test>", ":", "<test>"], [":", "<test>", "<sliceop>"], ["<test>", ":", "<sliceop>"], ["<test>", ":", "<test>", "<sliceop>"]],
	"<sliceop>": [[":"], [":", "<test>"]],
	"<exprlist>": [["<expr>"], ["<star_expr>"], ["<expr>", ",", "<exprlist>"], ["<star_expr>", ",", "<exprlist>"]],
	"<testlist>": [["<test>"], ["<test>", ",", "<testlist>"]],
	"<aux_test_seq>": [[], [",", "<test>", ":", "<test>", "<aux_test_seq>"]],
	"<aux_test_seq2>": [[], [",", "<test>", "<aux_test_seq>"]],
	"<dictorsetmaker>": [["<test>", ":", "<test>", " ", "<comp_for>"],
		["<test>", ":", "<test>", " ", "<aux_test_seq>"],
		["<test>", " ", "<comp_for>"],
		["<test>", " ", "<aux_test_seq2>"]],
	
	"<classdef>": [["class ", "<NAME>", "(", "<arglist>", ")", ":", "<suite>"], ["class ", "<NAME>", "()", ":", "<suite>"], ["class ", "<NAME>", ":", "<suite>"]],
	
	"<aux_arugment_seq>": [[], ["<argument>", ",", "<aux_arugment_seq>"]],
	"<arglist>": [["<aux_arugment_seq>", "**", "<test>"], ["<aux_arugment_seq>","<argument>"], ["<aux_arugment_seq>", "*", "<test>", ",", "<aux_arugment_seq>", "**", "<test>"], ["<aux_arugment_seq>", "*", "<test>", ",", "<aux_arugment_seq>"]],
	"<argument>": [["<NAME>"], ["<NAME>", "<comp_for>"], ["<NAME>", "=", "<test>"]],
	"<comp_iter>": [["<comp_for>"], ["<comp_if>"]],
	"<comp_for>": [["for ", "<exprlist>", " in ", "<or_test>"], ["for ", "<exprlist>", " in ", "<or_test>", "<comp_iter>"]],
	"<comp_if>": [["if ", "<test_nocond>"], ["if ", "<test_nocond> ", "<comp_iter>"]],
	
	"<yield_expr>": [["yield"], ["yield ", "<yield_arg>"]],
	"<yield_arg>": [["from ", "<test>"], ["from ", "<testlist>"]],
	"<NAME>": [["a"], ["b"], ["foo"], ["bar"], ["foobar"]],
	"<IMODULE_NAME>": [["math"]],
	"<NEWLINE>": [["\n"]],
	"<STRING>": [["'asd'"], ["(0x1000 * 'a')"], ["'aaaaaaaaaaaabbbbbbbbbbbbbbbb'"], ["'zarakatunga'"]],
	"<NUMBER>": [["0"], ["1"], ["0.1"], ["1/2"], ["-1"], ["11111111111"], ["1e100"], ["1e-100"], ["1e999999"], ["3.14"]]
}
```

I've run `afl-fuzz` with gdb, let it run for some minutes and interrupted it in order to check where it was hanging and got this backtrace (the same after several tries):

```
[...]
#61 0x00007fffeebd69dc in antlr4::atn::LL1Analyzer::_LOOK (this=0x7fffffffb340, s=0x555555637860, stopState=0x0, ctx=std::shared_ptr<antlr4::atn::PredictionContext> (use count 5, weak count 0) = {...}, look=..., lookBusy=std::unordered_set with 864043 elements = {...}, calledRuleStack=..., seeThruPreds=true, addEOF=true) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:136
#62 0x00007fffeebd6b2b in antlr4::atn::LL1Analyzer::_LOOK (this=0x7fffffffb340, s=0x555555637920, stopState=0x0, ctx=std::shared_ptr<antlr4::atn::PredictionContext> (use count 5, weak count 0) = {...}, look=..., lookBusy=std::unordered_set with 864043 elements = {...}, calledRuleStack=..., seeThruPreds=true, addEOF=true) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:145
#63 0x00007fffeebd6b2b in antlr4::atn::LL1Analyzer::_LOOK (this=0x7fffffffb340, s=0x555555634240, stopState=0x0, ctx=std::shared_ptr<antlr4::atn::PredictionContext> (use count 5, weak count 0) = {...}, look=..., lookBusy=std::unordered_set with 864043 elements = {...}, calledRuleStack=..., seeThruPreds=true, addEOF=true) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:145
#64 0x00007fffeebd69dc in antlr4::atn::LL1Analyzer::_LOOK (this=0x7fffffffb340, s=0x5555556394d0, stopState=0x0, ctx=std::shared_ptr<antlr4::atn::PredictionContext> (empty) = {...}, look=..., lookBusy=std::unordered_set with 864043 elements = {...}, calledRuleStack=..., seeThruPreds=true, addEOF=true) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:136
#65 0x00007fffeebd6b2b in antlr4::atn::LL1Analyzer::_LOOK (this=0x7fffffffb340, s=0x555555639770, stopState=0x0, ctx=std::shared_ptr<antlr4::atn::PredictionContext> (empty) = {...}, look=..., lookBusy=std::unordered_set with 864043 elements = {...}, calledRuleStack=..., seeThruPreds=true, addEOF=true) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:145
#66 0x00007fffeebd620b in antlr4::atn::LL1Analyzer::LOOK (this=0x7fffffffb340, s=0x555555639770, stopState=0x0, ctx=0x0) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:67
#67 0x00007fffeebd60d7 in antlr4::atn::LL1Analyzer::LOOK (this=0x7fffffffb340, s=0x555555639770, ctx=0x0) at antlr4-cpp-runtime-src/runtime/src/atn/LL1Analyzer.cpp:57
#68 0x00007fffeeba7aef in antlr4::atn::ATN::nextTokens (this=0x7fffeed46600 <GrammarParser::_atn>, s=0x555555639770, ctx=0x0) at antlr4-cpp-runtime-src/runtime/src/atn/ATN.cpp:86
#69 0x00007fffeeba7bd1 in antlr4::atn::ATN::nextTokens (this=0x7fffeed46600 <GrammarParser::_atn>, s=0x555555639770) at antlr4-cpp-runtime-src/runtime/src/atn/ATN.cpp:94
#70 0x00007fffeec45bb3 in antlr4::DefaultErrorStrategy::sync (this=0x555555664940, recognizer=0x7fffffffb750) at antlr4-cpp-runtime-src/runtime/src/DefaultErrorStrategy.cpp:103
#71 0x00007fffeeb2f354 in GrammarParser::node_program (this=0x7fffffffb750) at generated/GrammarParser.cpp:233
#72 0x00007fffeeb2eaff in GrammarParser::node_START (this=0x7fffffffb750) at generated/GrammarParser.cpp:132
#73 0x00007fffeeb2e668 in GrammarParser::entry (this=0x7fffffffb750) at generated/GrammarParser.cpp:75
#74 0x00007fffeeb226e6 in tree_from_buf (data_buf=0x7ffff7ffb000 "a=1\nb=1.203213\nfoo='123213'\nbar=b'123\\x01'\n1=a\n\n", data_size=48) at antlr4_shim.cpp:95
#75 0x00007fffeeb1c408 in load_tree_from_test_case (filename=0x5555556042c0 "out/default/queue/id:000000,time:0,execs:0,orig:0") at tree.c:861
#76 0x00007fffeeb1968f in afl_custom_queue_get (data=0x555555665d20, filename=0x5555556042c0 "out/default/queue/id:000000,time:0,execs:0,orig:0") at grammar_mutator.c:216
#77 0x00007fffeeb1a306 in afl_custom_queue_new_entry (data=0x555555665d20, filename_new_queue=0x5555556042c0 "out/default/queue/id:000000,time:0,execs:0,orig:0", filename_orig_queue=0x0) at grammar_mutator.c:681
#78 0x000055555557fb62 in run_afl_custom_queue_new_entry (afl=0x7ffff7552010, q=0x5555556610e0, fname=0x5555556042c0 "out/default/queue/id:000000,time:0,execs:0,orig:0", mother_fname=0x0) at src/afl-fuzz-mutators.c:41
#79 0x000055555559350f in pivot_inputs (afl=0x7ffff7552010) at src/afl-fuzz-init.c:1358
#80 0x000055555558b4d9 in main (argc=8, argv_orig=0x7fffffffdf18, envp=0x7fffffffdf60) at src/afl-fuzz.c:1832
```
Only part of the trace is included, from that point up it just repeats the last three calls.

Please let me know if I can provide any more info, or if you've got any hint as to what might be the problem.

**Comment by h1994st** [comment]
I will take a look later this week.

**Comment by h1994st** [comment]
My guess is that your python grammar has inappropriate recursive rules. For example,

```json
"<program>": [["<stmt>", "<NEWLINE>"], ["<stmt>", "<NEWLINE>", "<program>"]],
"<decorators>": [["<decorator>"], ["<decorator>", "<decorators>"]],
```

The two rules for `<program>` may result in ambiguity, as they look quite similar. There may exist other recursive rules in your grammar.

I would change them to the following rules to avoid ambiguity:

```json
"<program>": [["<stmt>", "<NEWLINE>", "<program>"], []],
"<decorators>": [["<decorator>", "<decorators>"], []],
```

This is just my guess, and need to check ANTLR4 documents for more information.

**Comment by h1994st** [comment]
Hi @OctavioGalland 

A temporary workaround is pushed: 4899a2f29acd2a2dfacff3d0bbb4d27c3f5317b7. You can give it a try.

The new commit fixes a naming issue. Since you are using the grammar generator to generate test cases, the new commit can help you avoid parsing during the initialization stage.

Still, the issue is not fully resolved, as it is actually caused by the ambiguity of the grammar. You can also confirm the infinite loop behavior using [ANTLR4](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md):

```bash
python grammars/f1_g4_translate.py ./grammars/python.json ./grammars  # Generate Grammar.g4
mkdir temp
cd temp
java -jar ../antlr-4.8-complete.jar ../grammars/Grammar.g4
javac -cp "../antlr-4.8-complete.jar:$CLASSPATH" Grammar*.java

java -cp "../antlr-4.8-complete.jar:$CLASSPATH" org.antlr.v4.gui.TestRig Grammar entry -tree -trace ../in/0
# the program will hang here
```

To fully address your issue, you may want to reach out to the ANTLR4 community for help to diagnose the root cause of the grammar.

**Comment by OctavioGalland** [comment]
I've tried the new commit and it worked great.
I had thought this might be related to antlr since afl hanged when calling `antlr4::DefaultErrorStrategy::sync`, but I wasn't aware of the fact that ambiguous grammar rules could cause trouble.

Thank you so much for your help!
